const AllModules = require('../assets/modules.json')

/* replace all spaces to underlines

cmd /e:on /v:on /c "for %f in ("* *.jpg") do (set "n=%~nxf" & set "n=!n: =_!" & ren "%~ff" "!n!" )"
cmd /e:on /v:on /c "for %f in ("* *.png") do (set "n=%~nxf" & set "n=!n: =_!" & ren "%~ff" "!n!" )"

*/

const requireModulesCover = {
    //do it in Excel :
    //=""""&A1&""" :  require(""../assets/module_covers/"&A1&"""),"
    "Acquire_Within_(Hard)__1.jpg" :  require("../assets/module_covers/Acquire_Within_(Hard)__1.jpg"),
    "Acquire_Within_(Hard)__2.jpg" :  require("../assets/module_covers/Acquire_Within_(Hard)__2.jpg"),
    "Acquire_Within_(Hard)__3.jpg" :  require("../assets/module_covers/Acquire_Within_(Hard)__3.jpg"),
    "Against_the_Cockroaches__1.jpg" :  require("../assets/module_covers/Against_the_Cockroaches__1.jpg"),
    "Against_the_Cockroaches__2.jpg" :  require("../assets/module_covers/Against_the_Cockroaches__2.jpg"),
    "Against_the_Cockroaches__3.jpg" :  require("../assets/module_covers/Against_the_Cockroaches__3.jpg"),
    "Assault_on_Castle_Mitternacht__1.jpg" :  require("../assets/module_covers/Assault_on_Castle_Mitternacht__1.jpg"),
    "Assault_on_Castle_Mitternacht__2.jpg" :  require("../assets/module_covers/Assault_on_Castle_Mitternacht__2.jpg"),
    "Assault_on_Castle_Mitternacht__3.jpg" :  require("../assets/module_covers/Assault_on_Castle_Mitternacht__3.jpg"),
    "Attack_of_the_War_Monkeys__1.jpg" :  require("../assets/module_covers/Attack_of_the_War_Monkeys__1.jpg"),
    "Attack_of_the_War_Monkeys__2.jpg" :  require("../assets/module_covers/Attack_of_the_War_Monkeys__2.jpg"),
    "Attack_of_the_War_Monkeys__3.jpg" :  require("../assets/module_covers/Attack_of_the_War_Monkeys__3.jpg"),
    "Attack_of_the_War_Monkeys__4.jpg" :  require("../assets/module_covers/Attack_of_the_War_Monkeys__4.jpg"),
    "Beneath_Tcotzac__1.jpg" :  require("../assets/module_covers/Beneath_Tcotzac__1.jpg"),
    "Beneath_Tcotzac__2.jpg" :  require("../assets/module_covers/Beneath_Tcotzac__2.jpg"),
    "Beneath_Tcotzac__3.jpg" :  require("../assets/module_covers/Beneath_Tcotzac__3.jpg"),
    "Beneath_the_Frozen_Earth__1.jpg" :  require("../assets/module_covers/Beneath_the_Frozen_Earth__1.jpg"),
    "Beneath_the_Frozen_Earth__2.jpg" :  require("../assets/module_covers/Beneath_the_Frozen_Earth__2.jpg"),
    "Beneath_the_Frozen_Earth__3.jpg" :  require("../assets/module_covers/Beneath_the_Frozen_Earth__3.jpg"),
    "Black_Oaken_Heart__1.jpg" :  require("../assets/module_covers/Black_Oaken_Heart__1.jpg"),
    "Black_Oaken_Heart__2.jpg" :  require("../assets/module_covers/Black_Oaken_Heart__2.jpg"),
    "Black_Oaken_Heart__3.jpg" :  require("../assets/module_covers/Black_Oaken_Heart__3.jpg"),
    "Black_Oaken_Heart__4.jpg" :  require("../assets/module_covers/Black_Oaken_Heart__4.jpg"),
    "Black_Plume_Mountain__1.jpg" :  require("../assets/module_covers/Black_Plume_Mountain__1.jpg"),
    "Black_Plume_Mountain__2.jpg" :  require("../assets/module_covers/Black_Plume_Mountain__2.jpg"),
    "Black_Plume_Mountain__3.jpg" :  require("../assets/module_covers/Black_Plume_Mountain__3.jpg"),
    "But_A_Trifle_(Hard)__1.jpg" :  require("../assets/module_covers/But_A_Trifle_(Hard)__1.jpg"),
    "But_A_Trifle_(Hard)__2.jpg" :  require("../assets/module_covers/But_A_Trifle_(Hard)__2.jpg"),
    "But_A_Trifle_(Hard)__3.jpg" :  require("../assets/module_covers/But_A_Trifle_(Hard)__3.jpg"),
    "CardStock_II_Secret_Preview__1.jpg" :  require("../assets/module_covers/CardStock_II_Secret_Preview__1.jpg"),
    "CardStock_II_Secret_Preview__2.jpg" :  require("../assets/module_covers/CardStock_II_Secret_Preview__2.jpg"),
    "CardStock_II_Secret_Preview__3.jpg" :  require("../assets/module_covers/CardStock_II_Secret_Preview__3.jpg"),
    "Caverns_of_the_Troglodytes__1.jpg" :  require("../assets/module_covers/Caverns_of_the_Troglodytes__1.jpg"),
    "Caverns_of_the_Troglodytes__2.jpg" :  require("../assets/module_covers/Caverns_of_the_Troglodytes__2.jpg"),
    "Citrine_Demon_Portal__1.jpg" :  require("../assets/module_covers/Citrine_Demon_Portal__1.jpg"),
    "Citrine_Demon_Portal__2.jpg" :  require("../assets/module_covers/Citrine_Demon_Portal__2.jpg"),
    "Citrine_Demon_Portal__3.jpg" :  require("../assets/module_covers/Citrine_Demon_Portal__3.jpg"),
    "Citrine_Demon_Portal__4.jpg" :  require("../assets/module_covers/Citrine_Demon_Portal__4.jpg"),
    "Cliffs_of_the_Wyverns__1.jpg" :  require("../assets/module_covers/Cliffs_of_the_Wyverns__1.jpg"),
    "Cliffs_of_the_Wyverns__2.jpg" :  require("../assets/module_covers/Cliffs_of_the_Wyverns__2.jpg"),
    "Cliffs_of_the_Wyverns__3.jpg" :  require("../assets/module_covers/Cliffs_of_the_Wyverns__3.jpg"),
    "Cliffs_of_the_Wyverns__4.jpg" :  require("../assets/module_covers/Cliffs_of_the_Wyverns__4.jpg"),
    "Crystals_of_Chronak__1.jpg" :  require("../assets/module_covers/Crystals_of_Chronak__1.jpg"),
    "Crystals_of_Chronak__2.jpg" :  require("../assets/module_covers/Crystals_of_Chronak__2.jpg"),
    "Crystals_of_Chronak__3.jpg" :  require("../assets/module_covers/Crystals_of_Chronak__3.jpg"),
    "Descent_to_the_Core__1.jpg" :  require("../assets/module_covers/Descent_to_the_Core__1.jpg"),
    "Descent_to_the_Core__2.jpg" :  require("../assets/module_covers/Descent_to_the_Core__2.jpg"),
    "Descent_to_the_Core__3.jpg" :  require("../assets/module_covers/Descent_to_the_Core__3.jpg"),
    "Diamonds_of_the_Kobolds__1.jpg" :  require("../assets/module_covers/Diamonds_of_the_Kobolds__1.jpg"),
    "Diamonds_of_the_Kobolds__2.jpg" :  require("../assets/module_covers/Diamonds_of_the_Kobolds__2.jpg"),
    "Diamonds_of_the_Kobolds__3.jpg" :  require("../assets/module_covers/Diamonds_of_the_Kobolds__3.jpg"),
    "Dungeon_of_the_Lizard_Priest__1.jpg" :  require("../assets/module_covers/Dungeon_of_the_Lizard_Priest__1.jpg"),
    "Dungeon_of_the_Lizard_Priest__2.jpg" :  require("../assets/module_covers/Dungeon_of_the_Lizard_Priest__2.jpg"),
    "Dungeon_of_the_Lizard_Priest__3.jpg" :  require("../assets/module_covers/Dungeon_of_the_Lizard_Priest__3.jpg"),
    "Dungeon_of_the_Swamp_King__1.jpg" :  require("../assets/module_covers/Dungeon_of_the_Swamp_King__1.jpg"),
    "Dungeon_of_the_Swamp_King__2.jpg" :  require("../assets/module_covers/Dungeon_of_the_Swamp_King__2.jpg"),
    "Dungeon_of_the_Swamp_King__3.jpg" :  require("../assets/module_covers/Dungeon_of_the_Swamp_King__3.jpg"),
    "Dungeon_of_the_Swamp_King__4.jpg" :  require("../assets/module_covers/Dungeon_of_the_Swamp_King__4.jpg"),
    "Forest_of_Souls__1.jpg" :  require("../assets/module_covers/Forest_of_Souls__1.jpg"),
    "Forest_of_Souls__2.jpg" :  require("../assets/module_covers/Forest_of_Souls__2.jpg"),
    "Forest_of_Souls__3.jpg" :  require("../assets/module_covers/Forest_of_Souls__3.jpg"),
    "Garnet_Demon_Portal__1.jpg" :  require("../assets/module_covers/Garnet_Demon_Portal__1.jpg"),
    "Garnet_Demon_Portal__2.jpg" :  require("../assets/module_covers/Garnet_Demon_Portal__2.jpg"),
    "Garnet_Demon_Portal__3.jpg" :  require("../assets/module_covers/Garnet_Demon_Portal__3.jpg"),
    "Garnet_Demon_Portal__4.jpg" :  require("../assets/module_covers/Garnet_Demon_Portal__4.jpg"),
    "Garnet_Demon_Portal__5.jpg" :  require("../assets/module_covers/Garnet_Demon_Portal__5.jpg"),
    "Gladiatorial_Arena,_Finals__1.jpg" :  require("../assets/module_covers/Gladiatorial_Arena,_Finals__1.jpg"),
    "Gladiatorial_Arena,_Finals__2.jpg" :  require("../assets/module_covers/Gladiatorial_Arena,_Finals__2.jpg"),
    "Gladiatorial_Arena,_Finals__3.jpg" :  require("../assets/module_covers/Gladiatorial_Arena,_Finals__3.jpg"),
    "Gladiatorial_Arena,_Qualifiers__1.jpg" :  require("../assets/module_covers/Gladiatorial_Arena,_Qualifiers__1.jpg"),
    "Gladiatorial_Arena,_Qualifiers__2.jpg" :  require("../assets/module_covers/Gladiatorial_Arena,_Qualifiers__2.jpg"),
    "Gladiatorial_Arena,_Qualifiers__3.jpg" :  require("../assets/module_covers/Gladiatorial_Arena,_Qualifiers__3.jpg"),
    "Goblins_in_the_Woods__1.jpg" :  require("../assets/module_covers/Goblins_in_the_Woods__1.jpg"),
    "Goblins_in_the_Woods__2.jpg" :  require("../assets/module_covers/Goblins_in_the_Woods__2.jpg"),
    "Goblins_in_the_Woods__3.jpg" :  require("../assets/module_covers/Goblins_in_the_Woods__3.jpg"),
    "Goblins_in_the_Woods__4.jpg" :  require("../assets/module_covers/Goblins_in_the_Woods__4.jpg"),
    "Highway_Robbery__1.jpg" :  require("../assets/module_covers/Highway_Robbery__1.jpg"),
    "Highway_Robbery__2.jpg" :  require("../assets/module_covers/Highway_Robbery__2.jpg"),
    "Highway_Robbery__3.jpg" :  require("../assets/module_covers/Highway_Robbery__3.jpg"),
    "High_Mountain_Pass__1.jpg" :  require("../assets/module_covers/High_Mountain_Pass__1.jpg"),
    "High_Mountain_Pass__2.jpg" :  require("../assets/module_covers/High_Mountain_Pass__2.jpg"),
    "High_Mountain_Pass__3.jpg" :  require("../assets/module_covers/High_Mountain_Pass__3.jpg"),
    "High_Mountain_Pass__4.jpg" :  require("../assets/module_covers/High_Mountain_Pass__4.jpg"),
    "Into_the_Black_Forest__1.jpg" :  require("../assets/module_covers/Into_the_Black_Forest__1.jpg"),
    "Into_the_Black_Forest__2.jpg" :  require("../assets/module_covers/Into_the_Black_Forest__2.jpg"),
    "Into_the_Black_Forest__3.jpg" :  require("../assets/module_covers/Into_the_Black_Forest__3.jpg"),
    "Into_the_Black_Forest__4.jpg" :  require("../assets/module_covers/Into_the_Black_Forest__4.jpg"),
    "In_the_Belly_of_the_Beast__1.jpg" :  require("../assets/module_covers/In_the_Belly_of_the_Beast__1.jpg"),
    "In_the_Belly_of_the_Beast__2.jpg" :  require("../assets/module_covers/In_the_Belly_of_the_Beast__2.jpg"),
    "In_the_Belly_of_the_Beast__3.jpg" :  require("../assets/module_covers/In_the_Belly_of_the_Beast__3.jpg"),
    "Lair_of_the_Trog_Wizard__1.jpg" :  require("../assets/module_covers/Lair_of_the_Trog_Wizard__1.jpg"),
    "Lair_of_the_Trog_Wizard__2.jpg" :  require("../assets/module_covers/Lair_of_the_Trog_Wizard__2.jpg"),
    "Lair_of_the_Yellow_Dragon__1.jpg" :  require("../assets/module_covers/Lair_of_the_Yellow_Dragon__1.jpg"),
    "Lair_of_the_Yellow_Dragon__2.jpg" :  require("../assets/module_covers/Lair_of_the_Yellow_Dragon__2.jpg"),
    "Lair_of_the_Yellow_Dragon__3.jpg" :  require("../assets/module_covers/Lair_of_the_Yellow_Dragon__3.jpg"),
    "Lair_of_the_Yellow_Dragon__4.jpg" :  require("../assets/module_covers/Lair_of_the_Yellow_Dragon__4.jpg"),
    "Lord_Batford's_Manor__1.jpg" :  require("../assets/module_covers/Lord_Batford's_Manor__1.jpg"),
    "Lord_Batford's_Manor__2.jpg" :  require("../assets/module_covers/Lord_Batford's_Manor__2.jpg"),
    "Lord_Batford's_Manor__3.jpg" :  require("../assets/module_covers/Lord_Batford's_Manor__3.jpg"),
    "Lord_Batford's_Manor__4.jpg" :  require("../assets/module_covers/Lord_Batford's_Manor__4.jpg"),
    "Lord_Batford's_Manor__5.jpg" :  require("../assets/module_covers/Lord_Batford's_Manor__5.jpg"),
    "Lord_Batford's_Manor__6.jpg" :  require("../assets/module_covers/Lord_Batford's_Manor__6.jpg"),
    "Lord_Stafford's_Treasure__1.jpg" :  require("../assets/module_covers/Lord_Stafford's_Treasure__1.jpg"),
    "Lord_Stafford's_Treasure__2.jpg" :  require("../assets/module_covers/Lord_Stafford's_Treasure__2.jpg"),
    "Lord_Stafford's_Treasure__3.jpg" :  require("../assets/module_covers/Lord_Stafford's_Treasure__3.jpg"),
    "Melvelous_the_Magnificent__1.jpg" :  require("../assets/module_covers/Melvelous_the_Magnificent__1.jpg"),
    "Melvelous_the_Magnificent__2.jpg" :  require("../assets/module_covers/Melvelous_the_Magnificent__2.jpg"),
    "Melvelous_the_Magnificent__3.jpg" :  require("../assets/module_covers/Melvelous_the_Magnificent__3.jpg"),
    "Order_of_the_Core__1.jpg" :  require("../assets/module_covers/Order_of_the_Core__1.jpg"),
    "Order_of_the_Core__2.jpg" :  require("../assets/module_covers/Order_of_the_Core__2.jpg"),
    "Order_of_the_Core__3.jpg" :  require("../assets/module_covers/Order_of_the_Core__3.jpg"),
    "Passageways_to_Death__1.jpg" :  require("../assets/module_covers/Passageways_to_Death__1.jpg"),
    "Passageways_to_Death__2.jpg" :  require("../assets/module_covers/Passageways_to_Death__2.jpg"),
    "Passageways_to_Death__3.jpg" :  require("../assets/module_covers/Passageways_to_Death__3.jpg"),
    "Rescue_From_Shieldhaven_Prison__1.jpg" :  require("../assets/module_covers/Rescue_From_Shieldhaven_Prison__1.jpg"),
    "Rescue_From_Shieldhaven_Prison__2.jpg" :  require("../assets/module_covers/Rescue_From_Shieldhaven_Prison__2.jpg"),
    "Rescue_From_Shieldhaven_Prison__3.jpg" :  require("../assets/module_covers/Rescue_From_Shieldhaven_Prison__3.jpg"),
    "Rescue_From_Shieldhaven_Prison__4.jpg" :  require("../assets/module_covers/Rescue_From_Shieldhaven_Prison__4.jpg"),
    "Return_to_the_Astral_Shrine__1.jpg" :  require("../assets/module_covers/Return_to_the_Astral_Shrine__1.jpg"),
    "Return_to_the_Astral_Shrine__2.jpg" :  require("../assets/module_covers/Return_to_the_Astral_Shrine__2.jpg"),
    "Return_to_Woodhome__1.jpg" :  require("../assets/module_covers/Return_to_Woodhome__1.jpg"),
    "Return_to_Woodhome__2.jpg" :  require("../assets/module_covers/Return_to_Woodhome__2.jpg"),
    "Riddle_of_the_Gnome_Lords__1.jpg" :  require("../assets/module_covers/Riddle_of_the_Gnome_Lords__1.jpg"),
    "Riddle_of_the_Gnome_Lords__2.jpg" :  require("../assets/module_covers/Riddle_of_the_Gnome_Lords__2.jpg"),
    "Riddle_of_the_Gnome_Lords__3.jpg" :  require("../assets/module_covers/Riddle_of_the_Gnome_Lords__3.jpg"),
    "Ruby_Demon_Portal__1.jpg" :  require("../assets/module_covers/Ruby_Demon_Portal__1.jpg"),
    "Ruby_Demon_Portal__2.jpg" :  require("../assets/module_covers/Ruby_Demon_Portal__2.jpg"),
    "Ruby_Demon_Portal__3.jpg" :  require("../assets/module_covers/Ruby_Demon_Portal__3.jpg"),
    "Sanctum_of_the_Cyber_Tyrant__1.jpg" :  require("../assets/module_covers/Sanctum_of_the_Cyber_Tyrant__1.jpg"),
    "Sanctum_of_the_Cyber_Tyrant__2.jpg" :  require("../assets/module_covers/Sanctum_of_the_Cyber_Tyrant__2.jpg"),
    "Sanctum_of_the_Cyber_Tyrant__3.jpg" :  require("../assets/module_covers/Sanctum_of_the_Cyber_Tyrant__3.jpg"),
    "Secret_of_the_Elder_Mind__1.jpg" :  require("../assets/module_covers/Secret_of_the_Elder_Mind__1.jpg"),
    "Secret_of_the_Elder_Mind__2.jpg" :  require("../assets/module_covers/Secret_of_the_Elder_Mind__2.jpg"),
    "Secret_of_the_Elder_Mind__3.jpg" :  require("../assets/module_covers/Secret_of_the_Elder_Mind__3.jpg"),
    "Secret_of_the_Gnome_Lords__1.jpg" :  require("../assets/module_covers/Secret_of_the_Gnome_Lords__1.jpg"),
    "Secret_of_the_Gnome_Lords__2.jpg" :  require("../assets/module_covers/Secret_of_the_Gnome_Lords__2.jpg"),
    "Shrine_of_the_Astral_Guardians__1.jpg" :  require("../assets/module_covers/Shrine_of_the_Astral_Guardians__1.jpg"),
    "Shrine_of_the_Astral_Guardians__2.jpg" :  require("../assets/module_covers/Shrine_of_the_Astral_Guardians__2.jpg"),
    "Shrine_of_the_Astral_Guardians__3.jpg" :  require("../assets/module_covers/Shrine_of_the_Astral_Guardians__3.jpg"),
    "Slub_Gut's_Sanctum__1.jpg" :  require("../assets/module_covers/Slub_Gut's_Sanctum__1.jpg"),
    "Slub_Gut's_Sanctum__2.jpg" :  require("../assets/module_covers/Slub_Gut's_Sanctum__2.jpg"),
    "Svitlana's_Inquisition__1.jpg" :  require("../assets/module_covers/Svitlana's_Inquisition__1.jpg"),
    "Svitlana's_Inquisition__2.jpg" :  require("../assets/module_covers/Svitlana's_Inquisition__2.jpg"),
    "Svitlana's_Inquisition__3.jpg" :  require("../assets/module_covers/Svitlana's_Inquisition__3.jpg"),
    "Svitlana's_Inquisition__4.jpg" :  require("../assets/module_covers/Svitlana's_Inquisition__4.jpg"),
    "Temple_of_Scales__1.jpg" :  require("../assets/module_covers/Temple_of_Scales__1.jpg"),
    "Temple_of_Scales__2.jpg" :  require("../assets/module_covers/Temple_of_Scales__2.jpg"),
    "Temple_of_Scales__3.jpg" :  require("../assets/module_covers/Temple_of_Scales__3.jpg"),
    "Temple_of_Scales__4.jpg" :  require("../assets/module_covers/Temple_of_Scales__4.jpg"),
    "Temple_of_Terror__1.jpg" :  require("../assets/module_covers/Temple_of_Terror__1.jpg"),
    "Temple_of_Terror__2.jpg" :  require("../assets/module_covers/Temple_of_Terror__2.jpg"),
    "Temple_of_Terror__3.jpg" :  require("../assets/module_covers/Temple_of_Terror__3.jpg"),
    "The_Compass_of_Xorr__1.jpg" :  require("../assets/module_covers/The_Compass_of_Xorr__1.jpg"),
    "The_Compass_of_Xorr__2.jpg" :  require("../assets/module_covers/The_Compass_of_Xorr__2.jpg"),
    "The_Compass_of_Xorr__3.jpg" :  require("../assets/module_covers/The_Compass_of_Xorr__3.jpg"),
    "The_Defense_of_Woodhome__1.jpg" :  require("../assets/module_covers/The_Defense_of_Woodhome__1.jpg"),
    "The_Defense_of_Woodhome__2.jpg" :  require("../assets/module_covers/The_Defense_of_Woodhome__2.jpg"),
    "The_Defense_of_Woodhome__3.jpg" :  require("../assets/module_covers/The_Defense_of_Woodhome__3.jpg"),
    "The_Jewel_of_Alet_Zhav__1.jpg" :  require("../assets/module_covers/The_Jewel_of_Alet_Zhav__1.jpg"),
    "The_Jewel_of_Alet_Zhav__2.jpg" :  require("../assets/module_covers/The_Jewel_of_Alet_Zhav__2.jpg"),
    "The_Jewel_of_Alet_Zhav__3.jpg" :  require("../assets/module_covers/The_Jewel_of_Alet_Zhav__3.jpg"),
    "The_Jewel_of_Alet_Zhav__4.jpg" :  require("../assets/module_covers/The_Jewel_of_Alet_Zhav__4.jpg"),
    "The_Metallic_Monstrosity__1.jpg" :  require("../assets/module_covers/The_Metallic_Monstrosity__1.jpg"),
    "The_Metallic_Monstrosity__2.jpg" :  require("../assets/module_covers/The_Metallic_Monstrosity__2.jpg"),
    "The_Metallic_Monstrosity__3.jpg" :  require("../assets/module_covers/The_Metallic_Monstrosity__3.jpg"),
    "The_Perilous_Garden__1.jpg" :  require("../assets/module_covers/The_Perilous_Garden__1.jpg"),
    "The_Perilous_Garden__2.jpg" :  require("../assets/module_covers/The_Perilous_Garden__2.jpg"),
    "The_Perilous_Garden__3.jpg" :  require("../assets/module_covers/The_Perilous_Garden__3.jpg"),
    "The_Pools_of_Slime__1.jpg" :  require("../assets/module_covers/The_Pools_of_Slime__1.jpg"),
    "The_Pools_of_Slime__2.jpg" :  require("../assets/module_covers/The_Pools_of_Slime__2.jpg"),
    "The_Pools_of_Slime__3.jpg" :  require("../assets/module_covers/The_Pools_of_Slime__3.jpg"),
    "The_Sinister_Wood__1.jpg" :  require("../assets/module_covers/The_Sinister_Wood__1.jpg"),
    "The_Sinister_Wood__2.jpg" :  require("../assets/module_covers/The_Sinister_Wood__2.jpg"),
    "The_Sinister_Wood__3.jpg" :  require("../assets/module_covers/The_Sinister_Wood__3.jpg"),
    "The_Spreading_Blight__1.jpg" :  require("../assets/module_covers/The_Spreading_Blight__1.jpg"),
    "The_Spreading_Blight__2.jpg" :  require("../assets/module_covers/The_Spreading_Blight__2.jpg"),
    "The_Spreading_Blight__3.jpg" :  require("../assets/module_covers/The_Spreading_Blight__3.jpg"),
    "The_Throne_of_Strench__1.jpg" :  require("../assets/module_covers/The_Throne_of_Strench__1.jpg"),
    "The_Throne_of_Strench__2.jpg" :  require("../assets/module_covers/The_Throne_of_Strench__2.jpg"),
    "The_Throne_of_Strench__3.jpg" :  require("../assets/module_covers/The_Throne_of_Strench__3.jpg"),
    "The_Tomb_of_Tvericus__1.jpg" :  require("../assets/module_covers/The_Tomb_of_Tvericus__1.jpg"),
    "The_Tomb_of_Tvericus__2.jpg" :  require("../assets/module_covers/The_Tomb_of_Tvericus__2.jpg"),
    "The_Tomb_of_Tvericus__3.jpg" :  require("../assets/module_covers/The_Tomb_of_Tvericus__3.jpg"),
    "The_Tomb_of_Tvericus__4.jpg" :  require("../assets/module_covers/The_Tomb_of_Tvericus__4.jpg"),
    "The_Troll_Tyrant__1.jpg" :  require("../assets/module_covers/The_Troll_Tyrant__1.jpg"),
    "The_Troll_Tyrant__2.jpg" :  require("../assets/module_covers/The_Troll_Tyrant__2.jpg"),
    "The_Troll_Tyrant__3.jpg" :  require("../assets/module_covers/The_Troll_Tyrant__3.jpg"),
    "The_Troll_Tyrant__4.jpg" :  require("../assets/module_covers/The_Troll_Tyrant__4.jpg"),
    "The_Viscous_Tombs__1.jpg" :  require("../assets/module_covers/The_Viscous_Tombs__1.jpg"),
    "The_Viscous_Tombs__2.jpg" :  require("../assets/module_covers/The_Viscous_Tombs__2.jpg"),
    "The_Viscous_Tombs__3.jpg" :  require("../assets/module_covers/The_Viscous_Tombs__3.jpg"),
    "The_White_Star__1.jpg" :  require("../assets/module_covers/The_White_Star__1.jpg"),
    "The_White_Star__2.jpg" :  require("../assets/module_covers/The_White_Star__2.jpg"),
    "The_White_Star__3.jpg" :  require("../assets/module_covers/The_White_Star__3.jpg"),
    "The_Wizard's_Workshop__1.jpg" :  require("../assets/module_covers/The_Wizard's_Workshop__1.jpg"),
    "The_Wizard's_Workshop__2.jpg" :  require("../assets/module_covers/The_Wizard's_Workshop__2.jpg"),
    "The_Wizard's_Workshop__3.jpg" :  require("../assets/module_covers/The_Wizard's_Workshop__3.jpg"),
    "Throne_of_the_Mechanical_Men__1.jpg" :  require("../assets/module_covers/Throne_of_the_Mechanical_Men__1.jpg"),
    "Throne_of_the_Mechanical_Men__2.jpg" :  require("../assets/module_covers/Throne_of_the_Mechanical_Men__2.jpg"),
    "Throne_of_the_Mechanical_Men__3.jpg" :  require("../assets/module_covers/Throne_of_the_Mechanical_Men__3.jpg"),
    "Tomb of Savings (Hard)__2.png" :  require("../assets/module_covers/Tomb of Savings (Hard)__2.png"),
    "Tomb_of_Savings_(Hard)__1.jpg" :  require("../assets/module_covers/Tomb_of_Savings_(Hard)__1.jpg"),
    "Tomb_of_Savings_(Hard)__3.jpg" :  require("../assets/module_covers/Tomb_of_Savings_(Hard)__3.jpg"),
    "Tree_Forts_of_the_Goblin_King__1.jpg" :  require("../assets/module_covers/Tree_Forts_of_the_Goblin_King__1.jpg"),
    "Tree_Forts_of_the_Goblin_King__2.jpg" :  require("../assets/module_covers/Tree_Forts_of_the_Goblin_King__2.jpg"),
    "Tree_Forts_of_the_Goblin_King__3.jpg" :  require("../assets/module_covers/Tree_Forts_of_the_Goblin_King__3.jpg"),
    "Valley_of_Tezkal__1.jpg" :  require("../assets/module_covers/Valley_of_Tezkal__1.jpg"),
    "Valley_of_Tezkal__2.jpg" :  require("../assets/module_covers/Valley_of_Tezkal__2.jpg"),
    "Valley_of_Tezkal__3.jpg" :  require("../assets/module_covers/Valley_of_Tezkal__3.jpg"),
    "Eastpass_in_Effigy__1.jpg" :  require("../assets/module_covers/Eastpass_in_Effigy__1.jpg"),
    "Eastpass_in_Effigy__2.jpg" :  require("../assets/module_covers/Eastpass_in_Effigy__2.jpg"),
    "Eastpass_in_Effigy__3.jpg" :  require("../assets/module_covers/Eastpass_in_Effigy__3.jpg"),
    "Lair_of_the_Lithomancer__1.jpg" :  require("../assets/module_covers/Lair_of_the_Lithomancer__1.jpg"),
    "Lair_of_the_Lithomancer__2.jpg" :  require("../assets/module_covers/Lair_of_the_Lithomancer__2.jpg"),
    "Lair_of_the_Lithomancer__3.jpg" :  require("../assets/module_covers/Lair_of_the_Lithomancer__3.jpg"),
    "The_Beguiling_Bush__1.jpg" :  require("../assets/module_covers/The_Beguiling_Bush__1.jpg"),
    "The_Beguiling_Bush__2.jpg" :  require("../assets/module_covers/The_Beguiling_Bush__2.jpg"),
    "The_Beguiling_Bush__3.jpg" :  require("../assets/module_covers/The_Beguiling_Bush__3.jpg"),
    "The_Grasping_Grove__1.jpg" :  require("../assets/module_covers/The_Grasping_Grove__1.jpg"),
    "The_Grasping_Grove__2.jpg" :  require("../assets/module_covers/The_Grasping_Grove__2.jpg"),
    "The_Grasping_Grove__3.jpg" :  require("../assets/module_covers/The_Grasping_Grove__3.jpg"),
    "The_Larcenous_River__1.jpg" :  require("../assets/module_covers/The_Larcenous_River__1.jpg"),
    "The_Larcenous_River__2.jpg" :  require("../assets/module_covers/The_Larcenous_River__2.jpg"),
    "The_Larcenous_River__3.jpg" :  require("../assets/module_covers/The_Larcenous_River__3.jpg"),
    "The_Pirate_Host__1.jpg" :  require("../assets/module_covers/The_Pirate_Host__1.jpg"),
    "The_Pirate_Host__2.jpg" :  require("../assets/module_covers/The_Pirate_Host__2.jpg"),
    "The_Pirate_Host__3.jpg" :  require("../assets/module_covers/The_Pirate_Host__3.jpg"),
    "Twilight_in_Eastpass__1.jpg" :  require("../assets/module_covers/Twilight_in_Eastpass__1.jpg"),
    "Twilight_in_Eastpass__2.jpg" :  require("../assets/module_covers/Twilight_in_Eastpass__2.jpg"),
    "Twilight_in_Eastpass__3.jpg" :  require("../assets/module_covers/Twilight_in_Eastpass__3.jpg"),

}

const dlcNameList = {
    'advSet1': 'O',
    'advSet2': 'AA',
    'advSet3': 'SC',
    'advSet4': 'AI',
    'advSet5': 'EC',
    'advSet6': 'CM',
    'advSet7': 'CF'
}

export {AllModules,requireModulesCover,dlcNameList}